# Generated by Django 3.2.5 on 2021-08-12 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0002_mobile_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_cart', 'in_cart'), ('order_place', 'order_place'), ('order_cancelled', 'order_cancelled')], default='in_cart', max_length=40)),
                ('user', models.CharField(max_length=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.mobile')),
            ],
        ),
    ]
