# Generated by Django 3.2.5 on 2021-08-13 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_mobile_brand'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('order_placed', 'order_placed'), ('dispatched', 'dispatched'), ('intransmit', 'intransmit'), ('deliverd', 'deliverd'), ('cancelled', 'cancelled')], default='order_placed', max_length=120)),
                ('user', models.CharField(max_length=120)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.mobile')),
            ],
        ),
    ]
